on: [push, workflow_dispatch]

jobs:
  compile-pdf:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Testing...  
        run:  ls -l
      - name: Installing python...
        run: sudo apt install python-is-python3
      - name: Installing Inkscape...
        run: sudo apt install inkscape
      - name: Installing pdftk...
        run: sudo apt install pdftk

      #- uses: agoryuno/actions@v3.3
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: cv-pdf
      #    path: output/goryunov_cv.pdf