name: "Build the PDF"
on: [push, workflow_dispatch]

jobs:
  compile-pdf:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Testing...  
        run:  ls -l
      - name: Installing python...
        run: sudo apt install python-is-python3
      - name: Installing Inkscape...
        run: sudo apt install inkscape
      - name: Installing pdftk...
        run: sudo apt install pdftk
      - name: Building PDF...
        run: /bin/sh build.sh
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add goryunov_cv.pdf
      - name: commit changed files
        run: git commit -m "Updating CV pdf"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master

      - uses: actions/upload-artifact@v3
        with:
          name: goryunov_cv.pdf
          path: goryunov_cv.pdf