name: compile-pdf-files
run-name: Compiling output PDFs
on: [push]

runs:
  using: 'docker'
  image: 'Dockerfile'

steps:
  - name: Upload PDF to repo
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: output/goryunov_cv.pdf