name: "Compile PDF"
description: "Compiling output PDFs"
on: [push, workflow-dispatch]

runs:
  using: 'composite'

  steps:
    - uses: docker://Dockerfile
    - uses: actions/upload-artifact@v3
      with:
        name: cv-pdf
        path: output/goryunov_cv.pdf