on: [push, workflow_dispatch]

jobs:
  compile-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: agoryuno/cv/compile-pdf
      - uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: output/goryunov_cv.pdf