on: [push, workflow_dispatch]

jobs:
  compile-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with: 
          repository: 'agoryuno/cv'
      - uses: agoryuno/actions@v3.2
      - uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: output/goryunov_cv.pdf